version: '3'

services:
 alinesno-eureke:
  image: registry.cn-shenzhen.aliyuncs.com/alinesno-cloud/alinesno-cloud-base-boot
  container_name: alinesno-cloud-base-boot
  ports:
    - "30002:30002"
  environment:
    MYSQL_HOST: 192.168.1.101
